id: P004266
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 11:06:03.261843
source_metadata:
  id: bdr:W00KG01510
  title: བོད་ཀྱི་རིག་གནས་ལོ་རྒྱུས་དཔྱད་གཞིའི་རྒྱུ་ཆ་བདམས་བསྒྲིགས་༔ ༢༦
  author: ''
  volumes:
    1a70cb0d4e6d4e47ab08877acbc3e87e:
      image_group_id: I1GS44102
      title: ''
      volume_number: 1
      total_pages: 136
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
