id: IBE6B84BB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T14:48:11+00:00'
last_modified: '2022-06-07T21:32:25.588785+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG01510
  title: བོད་ཀྱི་རིག་གནས་ལོ་རྒྱུས་དཔྱད་གཞིའི་རྒྱུ་ཆ་བདམས་བསྒྲིགས་༔ ༢༦
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    A41A:
      image_group_id: I1GS44102
      title: ''
      total_pages: 136
      order: 1
      base_file: A41A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
